
project_id = "avdwgvjhufslhqrrmxgo"
[functions.chat-with-ai]
verify_jwt = false
[functions.initiate-payu-payment]
verify_jwt = true
[functions.handle-payu-webhook-v2]
verify_jwt = false
[functions.verify-payu-payment]
verify_jwt = true
[functions.instagram-auth]
verify_jwt = true
[functions.generate-product-image]
verify_jwt = true
[functions.generate-product-metadata]
verify_jwt = true
[functions.check-video-status]
verify_jwt = false
[functions.retrieve-video-result]
verify_jwt = false
