
[build]
  command = "npm ci && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
