-- Migration: Add main_product_image_url to canvas_projects and description to canvas_scenes

-- Add main product image URL to projects table if it doesn't exist
-- This centralizes the primary product image used for generation.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'canvas_projects' AND column_name = 'main_product_image_url') THEN
    ALTER TABLE public.canvas_projects ADD COLUMN main_product_image_url TEXT;
  END IF;
END $$;

-- Add description field to scenes table if it doesn't exist
-- This stores text descriptions, potentially generated by agents.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'canvas_scenes' AND column_name = 'description') THEN
    ALTER TABLE public.canvas_scenes ADD COLUMN description TEXT;
  END IF;
END $$;

-- Add comment for clarity
COMMENT ON COLUMN public.canvas_projects.main_product_image_url IS 'Stores the primary product image URL for the entire project, used as default source for product shots.';
COMMENT ON COLUMN public.canvas_scenes.description IS 'Stores textual description of the scene, potentially generated by AI agents.';